### ISSUE TITLE
solr dies when running restoreindex command

### ISSUE THREAD

**Issue by ko-christ** [whitepages/solrcloud_manager#3]
I have a SolrCloud, all collection configuration data is handled in ZooKeeper.
Both Solr nodes and Zookeeper is containerized in Docker containers.
The directory to store backupindex files is an NFS mount. The backup was created by this tool with the backupindex command. The **restoreindex** command does not execute successfully, it fails, then the solr process dies unexpectedly.

`REQUEST: /autocomplete/replication command=restorestatus
RESPONSE (exception): org.apache.solr.client.solrj.SolrServerException: IOException occured when talking to server at: http://10.5.5.5:7777/solr
Error checking restore status, org.apache.solr.client.solrj.SolrServerException: IOException occured when talking to server at: http://10.5.5.5:7777/solr`

Full dump log
`---------------  T H R E A D  ---------------

Current thread (0x00007f485812d000):  JavaThread "restoreExecutor-18-thread-1-processing-x:autocomplete r:10.5.5.198:7737_solr_autocomplete autocomplete n:10.5.5.198:7737_solr snapshot.autocomplete s:shard1 c:autocomplete //opt//backups//autocompletetest//autocomplete//shard1" [_thread_in_Java, id=180, stack(0x00007f4860634000,0x00007f4860675000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 2 (BUS_ADRERR), si_addr: 0x00007f48618fe000

Registers:
RAX=0x00007f48618fe48e, RBX=0x000000000000048e, RCX=0x0000000000000247, RDX=0xffffffffffffff73
RSP=0x00007f4860673430, RBP=0x00007f4860673430, RSI=0x00000000f1ae3f30, RDI=0x00007f48618fe480
R8 =0x0000000000000000, R9 =0x000000000000048e, R10=0x00007f48710527c0, R11=0x00000000f1ae3aa0
R12=0x0000000000000000, R13=0x0000000000000000, R14=0x000000000000048e, R15=0x00007f485812d000
RIP=0x00007f4871052000, EFLAGS=0x0000000000010292, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f4860673430)
0x00007f4860673430:   00007f48606735e0 00007f4871ebd7e0
0x00007f4860673440:   0000048e606734a8 00000000f1ae0918
0x00007f4860673450:   00007f487100798d 00000000f1ae3aa0
0x00007f4860673460:   00000000f1ae1730 00007f4860673468
0x00007f4860673470:   00007f48848e23cd 00007f48606734c8
0x00007f4860673480:   00007f48606735e0 00007f4871b06e94
0x00007f4860673490:   00007f48848e23e0 0000000000000000
0x00007f48606734a0:   00007f48606734b8 d75cebbdccc07a00
0x00007f48606734b0:   00007f487100798d 00000000f1ae3770
0x00007f48606734c0:   0000000100000768 00007f485812d000
0x00007f48606734d0:   0000000000000802 0000000000004000
0x00007f48606734e0:   00007f4860673550 00007f48889c8e10
0x00007f48606734f0:   00000000f1ae0a08 000000000000048e
0x00007f4860673500:   00000000f1ae3aa0 00000000f1ae3aa0
0x00007f4860673510:   0000000000000000 d75cebbdccc07a00
0x00007f4860673520:   00007f4860673590 00007f485812d000
0x00007f4860673530:   0000000000000000 00007f4860b15c85
0x00007f4860673540:   00007f4860673bf0 00007f4858129670
0x00007f4860673550:   00007f4860673580 00007f48885f082a
0x00007f4860673560:   00007f48606735e0 00007f487100798d
0x00007f4860673570:   00000000000000bc 00007f487100798d
0x00007f4860673580:   000000000000048e 0000000000000000
0x00007f4860673590:   00000000f1ae3aa0 00000000f1ae0a08
0x00007f48606735a0:   00007f48606735a0 00007f4860b15cb0
0x00007f48606735b0:   00007f4860673620 00007f4860226a80
0x00007f48606735c0:   0000000000000000 00007f4860b15d30
0x00007f48606735d0:   00007f4860673580 00007f4860673608
0x00007f48606735e0:   00007f4860673668 00007f487100798d
0x00007f48606735f0:   000000000000048e 000000000000048e
0x00007f4860673600:   0000000000000000 000000000000048e
0x00007f4860673610:   00000000f1ae0a08 00000000f1ae0a08
0x00007f4860673620:   00000000f1ae0a60 00007f4860673628

Instructions: (pc=0x00007f4871052000)
0x00007f4871051fe0:   c6 04 f7 c1 01 00 00 00 74 08 66 8b 47 08 66 89
0x00007f4871051ff0:   46 08 48 33 c0 c9 c3 66 0f 1f 84 00 00 00 00 00
0x00007f4871052000:   48 8b 44 d7 e8 48 89 44 d6 e8 48 8b 44 d7 f0 48
0x00007f4871052010:   89 44 d6 f0 48 8b 44 d7 f8 48 89 44 d6 f8 48 8b

Register to memory mapping:

RAX=0x00007f48618fe48e is an unknown value
RBX=0x000000000000048e is an unknown value
RCX=0x0000000000000247 is an unknown value
RDX=0xffffffffffffff73 is an unknown value
RSP=0x00007f4860673430 is pointing into the stack for thread: 0x00007f485812d000
RBP=0x00007f4860673430 is pointing into the stack for thread: 0x00007f485812d000`

**Comment by randomstatistic** [comment]
Wow, that's pretty impressive. My first thought is that you might have found a Solr bug.
"restorestatus" is what it sounds like, just a request to check on the status of a prior restore request. The thread dump suggests the restore operation itself is failing though. It's worth figuring out what's going on, because if that's failing, there's a decent chance that the work in progress for SOLR-5750 would fail for you too - the underlying replication handler commands should be very similar.

Some stuff to try:
1. If, after making a backup, you shut down solr, and manually replace the contents of the data dir with the contents from the backup, does solr start ok and see a valid index?
2. It might be helpful to see more info about your test environment (like the clusterstatus command output)
3. If you add the --debug flag to any solrcloud_manager command, it'll print the actual http requests and full responses being made to the cluster, which can be useful if you suspect one of the commands is malformed or incorrect.

**Comment by ko-christ** [comment]
Thanks for the advice. I also suspect that we might have found a Solr bug.
Using direct API calls, I have found out that I cannot import the same backup twice, unless I rename it.

The result when I try to import the same backup twice is always the same. The first time it succeeds the second it fails with the same dump log and solr jvm dies unexpectedly. If I rename the backup before each restore then it works fine.

solrcloud_manager restores one backup I guess then it fails while trying to restore the same backup to another node.

**Comment by randomstatistic** [comment]
Huh, interesting. solrcloud_manager does indeed handle multiple replicas for a shard by restoring the same backup for that shard to each replica. 

It'd be relatively easy to handle replicas by restoring to the leaders, then forcing other replicas to resync. This would work around the bug as reported, (once) but I'm confident I tested this case and saw it working. Might have been an older version, but probably not older than 5.2.1.

I'll try to play around a little myself, I want to understand better.

**Comment by hdimitriou** [comment]
" ...then forcing other replicas to resync" how can you do that? 
From what I understand from the https://issues.apache.org/jira/browse/SOLR-5750 ticket concerning SolrCloud backup/restore it's an issue still unresolved.

**Comment by randomstatistic** [comment]
There's a different mechanism called "fetchindex" in the replication handler that basically asks a core to download the files from another (live) core via http. 

It's used under the hood when you use the addreplica collections api command, and solrcloud_manager uses it to allow cross-cluster copy of entire collections. I believe some people use this as another strategy for backups too, copying between collections as necessary.

**Comment by randomstatistic** [comment]
I messed around some more and I'm still unclear on why the first restore didn't work for you. I created two collections with replicationFactor 2, backed up one, and restored into the other. The first restore attempt worked, but the second restore for a given backup didn't work. 

I didn't get any errors or crashing, however I didn't have two machines with a shared NFS system handy, so I was just using a single node and /tmp. The problem, which is that the newly restored core is named according to the backup name, could certainly have filesystem-related behaviors, because it's trying to create/copy/delete the same directory.

I'm not sure I can find any path to getting a *second* restore of a given backup to work from the solrcloud_manager perspective. Renaming the backup would work, but it doesn't have access to the filesystem of the solrcloud nodes outside of the replication API, and the replication API doesn't allow you to specify the restored core name.

**Comment by ko-christ** [comment]
Managed to reproduce the JVM Crash bug using the `MMapDirectoryFactory` implementation with the default/example `mail` collection. This isolates the crash it in the combination of `MMapDirectoryFactory` and the restore functionality. 

More specifically 

the second restore call crashes the jvm when using the `MMapDirectoryFactory` implementation.
`<directoryFactory name="DirectoryFactory" class="${solr.directoryFactory:solr.MMapDirectoryFactory}">`

the second restore call does not take place when using default `NRTCachingDirectoryFactory` implementation.
`<directoryFactory name="DirectoryFactory" class="${solr.directoryFactory:solr.NRTCachingDirectoryFactory}"/>`

Both of those bugs are not related to `solrcloud_manager`, but to Solr (verified for 5.5.0).

**Comment by randomstatistic** [comment]
Ah, great, that explains why I'm not seeing it then. The config I've been testing with uses NRTCachingDirectoryFactory. I feel like you should comment about this on SOLR-8449, or in a separate solr jira. It's always possible what you're seeing a result of a more generic bug in MMapDirectoryFactory than just restoring a backup.

As far as solrcloud_manager goes, I've added some warning messages in the readme, and when running the command itself. Not much else I can do here, which is unfortunate, since this definitely limits the utility of backups < v5.5.1.
